annotations:
    screwdriver.cd/restrictPR: all
shared:
    image: node:12
jobs: 
    main:
        requires: [~commit, ~pr]
        steps:
            - hello: echo test
            - justtest: echo justtest
            - status: |
                meta set meta.status.coverage '{"status":"PENDING","message":"Coverage must be below 80%."}'
                meta set meta.status.findbugs '{"status":"SUCCESS","message":"No Bugs Found!"}'
    something:
        requires: [~pr]
        steps:
            - hello: echo hello
    detached:
        requires: []
        steps:
            - hello: echo hello